# Stage 1: Build the React app
FROM node:20-alpine AS build

# Set the working directory
WORKDIR /app

# Ensure the app directory is writable by the container
#RUN mkdir -p /app/build && chmod -R 777 /app

# Copy the package.json and package-lock.json first
COPY ./frontend/package*.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the application code
COPY ./frontend ./

# Build the React app
RUN npm run build

# Stage 2: Serve the React app with Nginx
FROM nginx:1.26.2-alpine

# Copy the build from the previous stage to Nginx's html directory
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom Nginx config
COPY ./docker/nginx/nginx.prod.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]