# Use official PHP 8.2 image
FROM php:8.2-fpm

# Install necessary system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    vim \
    cron \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www

# Copy the Laravel project from local to container (if you want to persist local copy)
COPY ./backend .

# Install Laravel dependencies inside the container
RUN composer install --no-scripts --no-interaction && \
    php artisan key:generate

# Add the laravel scheduler to the crontab
RUN echo "* * * * * cd /var/www && /usr/local/bin/php artisan schedule:run >> /var/log/cron.log 2>&1" | crontab -

# Set vi as the default editor for crontab
RUN echo "export EDITOR=vi" >> ~/.bashrc

# Expose PHP-FPM on port 9000
CMD ["sh", "-c", "cron && php-fpm"]

EXPOSE 9000
