# Use official Node.js 20 image
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Ensure the app directory is writable by the container
#RUN mkdir -p /app/build && chmod -R 777 /app

# Copy the package.json and package-lock.json first
COPY ./frontend/package*.json ./

# Install the project dependencies
RUN npm install

# Copy the rest of the application code
COPY ./frontend .