version: '3.8'

services:
  news-aggregator-frontend:
    build:
      context: .
      dockerfile: Dockerfile-react-dev
    container_name: react-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - news-network

  news-aggregator-php:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: laravel-app
    volumes:
      - ./backend:/var/www
      - /var/www/vendor
    networks:
      - news-network

  news-aggregator-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: news_aggregator
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - news-network

  news-aggregator-webserver:
    image: nginx:1.26.2-alpine
    container_name: nginx-webserver
    ports:
      - "80:80"   # React app on port 80
      - "8080:8080"  # Laravel backend on port 8080
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf  # Use development Nginx config
    depends_on:
      - news-aggregator-frontend
      - news-aggregator-php
    networks:
      - news-network

networks:
  news-network:
    driver: bridge

volumes:
  dbdata:
